name: BeyondHorizons
version: ${project.version}
author: Slimeyderp
description: A generic Slimefun4-Addon made by SlimeyDerp
website: https://github.com/TheBusyBiscuit/Slimefun4-Addon

main: me.slimeyderp.beyondhorizons.BeyondHorizons
depend: [Slimefun]

api-version: 1.14
