name: BeyondHorizons
version: 1.0.2
main: me.slimeyderp.beyondhorizons.BeyondHorizons
author: Anvi
description: A generic Slimefun4-Addon made by SlimeyDerp
website: https://github.com/TheBusyBiscuit/Slimefun4-Addon
depend: [Slimefun]

api-version: 1.16